import './globals.css';
import { Inter } from 'next/font/google';
import { NextAuthProvider } from './providers';

import NavBar from '@/components/NavBar/NavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <NextAuthProvider>
        <body className={`min-h-screen  ${inter.className}`}>
          <NavBar/>
          <main className="flex flex-col p-6 sm:p-24 text-center md:text-left">
            {children}
          </main>
        </body>
      </NextAuthProvider>
    </html>
  );
}
