import './globals.css';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { NextAuthProvider } from './providers';
import SignInOutButton from '@/components/button/SignInOutButton';
import { authOptions } from './api/auth/[...nextauth]/route';
import { getServerSession } from 'next-auth';
import NavbarCenterButtons from '@/components/NavbarCenterButtons';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang='en'>
      <NextAuthProvider>
        <body className={inter.className}>
          <div className='navbar bg-base-100 drop-shadow'>
            <div className='navbar-start'>
              <Link href='/' className='btn btn-ghost normal-case text-xl font-bold'>
                Room Master
              </Link>
            </div>
            <div className='navbar-center'>
              <NavbarCenterButtons session={session}/>
            </div>
            <div className='navbar-end'>
              <SignInOutButton session={session} />
            </div>
          </div>
          <main className="flex min-h-screen flex-col p-24 text-center md:text-left">
            {children}
          </main>
        </body>
      </NextAuthProvider>
    </html>
  );
}
